name: MoreLoomLayers
version: '${version}'
main: me.bear.moreLoomLayers.MoreLoomLayers
api-version: '1.21'
authors: [ "Bearofbusiness" ]
commands:
  showbannerlayers:
    description: Shows the layers of a banner
    aliases: [sbl]
